######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 7 18:09:32 2014
#edited to remove web_crawler.cpp as a source
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . lib src
INCLUDEPATH += . lib src

# Input
HEADERS += mainwin.h pagewin.h lib/msort.h lib/Set.h src/WebPage.h
SOURCES += main.cpp mainwin.cpp pagewin.cpp src/WebPage.cpp
